// All the information for the quiz in an array of objects
let patternsArray = [
  {
    id: "1",
    choices: ["Love", "Hate", "Pain", "Hope"],
    pattern: "img/patterns/love.svg",
    answer: "answer1",
  },
  {
    id: "2",
    choices: ["Heat", "Hate", "Bliss", "Light"],
    pattern: "img/patterns/hate.svg",
    answer: "answer2",
  },
  {
    id: "3",
    choices: ["Calm", "Brutality", "Bliss", "Natural"],
    pattern: "img/patterns/brutality.svg",
    answer: "answer2",
  },
  {
    id: "4",
    choices: ["A lie", "Light", "Beauty", "Artificial"],
    pattern: "img/patterns/beauty.svg",
    answer: "answer3",
  },
  {
    id: "5",
    choices: ["Frivolous", "Light", "Original", "Closeness"],
    pattern: "img/patterns/closeness.svg",
    answer: "answer4",
  },
  {
    id: "6",
    choices: ["Cold", "Hate", "Beauty", "Light"],
    pattern: "img/patterns/cold.svg",
    answer: "answer1",
  },
  {
    id: "7",
    choices: ["A lie", "Erotism", "Beauty", "Artificial"],
    pattern: "img/patterns/erotism.svg",
    answer: "answer2",
  },
  {
    id: "8",
    choices: ["Infidelity", "Artificial", "Extroversion", "Independence"],
    pattern: "img/patterns/extroversion.svg",
    answer: "answer3",
  },
  {
    id: "9",
    choices: ["A lie", "Light", "Beauty", "Fun"],
    pattern: "img/patterns/fun.svg",
    answer: "answer4",
  },
  {
    id: "10",
    choices: ["Kindness", "Hate", "Introversion", "Independence"],
    pattern: "img/patterns/independence.svg",
    answer: "answer4",
  },
  {
    id: "11",
    choices: ["Infidelity", "Light", "Beauty", "Artificial"],
    pattern: "img/patterns/infidelity.svg",
    answer: "answer1",
  },
  {
    id: "12",
    choices: ["Light", "Introversion", "Erotism", "Infidelity"],
    pattern: "img/patterns/introversion.svg",
    answer: "answer2",
  },
  {
    id: "13",
    choices: ["A lie", "Light", "Kindness", "Artificial"],
    pattern: "img/patterns/kindness.svg",
    answer: "answer3",
  },
  {
    id: "14",
    choices: ["Love", "Hate", "Optimism", "Hope"],
    pattern: "img/patterns/optimism.svg",
    answer: "answer3",
  },
  {
    id: "15",
    choices: ["Artificial", "Introversion", "Optimism", "Selfishness"],
    pattern: "img/patterns/selfishness.svg",
    answer: "answer4",
  },
  {
    id: "16",
    choices: ["Erotism", "Power", "The Cold", "Kindness"],
    pattern: "img/patterns/power.svg",
    answer: "answer2",
  },
  {
    id: "17",
    choices: ["Optimism", "Power", "Rest", "A lie"],
    pattern: "img/patterns/rest.svg",
    answer: "answer3",
  },
  {
    id: "18",
    choices: ["Strength", "Light", "Rest", "Introversion"],
    pattern: "img/patterns/strength.svg",
    answer: "answer1",
  },
  {
    id: "19",
    choices: ["Artificial", "Trust", "Fantasy", "Harmony"],
    pattern: "img/patterns/fantasy.svg",
    answer: "answer3",
  },
  {
    id: "20",
    choices: ["Strength", "Optimism", "Fantasy", "Forbidden"],
    pattern: "img/patterns/forbidden.svg",
    answer: "answer4",
  },
  {
    id: "21",
    choices: ["Poisonous", "Trust", "Love", "Forbidden"],
    pattern: "img/patterns/poisonous.svg",
    answer: "answer1",
  },
  {
    id: "22",
    choices: ["Truth", "Courtesy", "Power", "Beauty"],
    pattern: "img/patterns/courtesy.svg",
    answer: "answer2",
  },
  {
    id: "23",
    choices: ["Pride", "Forbidden", "Happiness", "Luxury"],
    pattern: "img/patterns/happiness.svg",
    answer: "answer3",
  },
  {
    id: "24",
    choices: ["Pride", "Trust", "Beauty", "Optimism"],
    pattern: "img/patterns/pride.svg",
    answer: "answer1",
  },
  {
    id: "25",
    choices: ["Hope", "Rest", "Kindness", "Luxury"],
    pattern: "img/patterns/luxury.svg",
    answer: "answer4",
  },
  {
    id: "26",
    choices: ["Hope", "Modern", "Truth", "Poisonous"],
    pattern: "img/patterns/modern.svg",
    answer: "answer2",
  },
  {
    id: "27",
    choices: ["Hate", "Modern", "Dynamism", "Jealousy"],
    pattern: "img/patterns/dynamism.svg",
    answer: "answer3",
  },
  {
    id: "28",
    choices: ["Modern", "Hope", "Dynamism", "Healthy"],
    pattern: "img/patterns/healthy.svg",
    answer: "answer3",
  },
];

export default patternsArray;
