export let Cards = [
  {
    answer: "Love",
    choice1: "Love",
    choice2: "Hate",
    choice3: "Pain",
    choice4: "Hope",
    colour1: ["height : 90%", "background : #ff0000"],
    colour2: ["height : 0%", "background : #ff0000"],
    colour3: ["height : 0%", "background : #ff0000"],
    colour4: ["height : 10%", "background : #ea6284"],
  },
  {
    answer: "Hate",
    choice1: "Love",
    choice2: "Hate",
    choice3: "Pain",
    choice4: "Hope",
    colour1: ["height : 55%", "background : #ff0000"],
    colour2: ["height : 0%", "background : #ff0000"],
    colour3: ["height : 35%", "background : #000"],
    colour4: ["height : 10%", "background : #fff504"],
  },
  {
    answer: "Heat",
    choice1: "Calm",
    choice2: "Heat",
    choice3: "Excitement",
    choice4: "Natural",
    colour1: ["height : 55%", "background : #ff0000"],
    colour2: ["height : 0%", "background : #ff0000"],
    colour3: ["height : 35%", "background : #fff504"],
    colour4: ["height : 10%", "background : #ffa504"],
  },
  {
    answer: "Beauty",
    choice1: "The Lie",
    choice2: "Light",
    choice3: "Beauty",
    choice4: "Artificial",
    colour1: ["height : 25%", "background : #646835"],
    colour2: ["height : 26%", "background : #fff"],
    colour3: ["height : 29%", "background : #ff0000"],
    colour4: ["height : 20%", "background : #6C8491"],
  },
  {
    answer: "Power",
    choice1: "Frivolous",
    choice2: "Light",
    choice3: "Original",
    choice4: "Power",
    colour1: ["height : 25%", "background : #646835"],
    colour2: ["height : 26%", "background : #fff"],
    colour3: ["height : 29%", "background : #ff0000"],
    colour4: ["height : 20%", "background : #6C8491"],
  },
];
